/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as DisparosClientesRouteImport } from './routes/disparos/clientes'
import { Route as DisparosMensagensRouteImport } from './routes/disparos/mensagens'
import { Route as DisparosReguasRouteImport } from './routes/disparos/reguas'
import { Route as LlmIndexRouteImport } from './routes/llm/index'
import { Route as WhatsappIndexRouteImport } from './routes/whatsapp/index'
import { Route as WhatsappMensagensRouteImport } from './routes/whatsapp/mensagens'
import { Route as WhatsappTemplatesRouteImport } from './routes/whatsapp/templates'
import { Route as LlmEventosIndexRouteImport } from './routes/llm/eventos/index'
import { Route as LlmEventosAtorRouteImport } from './routes/llm/eventos/$ator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const DisparosClientesRoute = DisparosClientesRouteImport.update({
  id: '/disparos/clientes',
  path: '/disparos/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const DisparosMensagensRoute = DisparosMensagensRouteImport.update({
  id: '/disparos/mensagens',
  path: '/disparos/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const DisparosReguasRoute = DisparosReguasRouteImport.update({
  id: '/disparos/reguas',
  path: '/disparos/reguas',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmIndexRoute = LlmIndexRouteImport.update({
  id: '/llm/',
  path: '/llm/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappIndexRoute = WhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappMensagensRoute = WhatsappMensagensRouteImport.update({
  id: '/whatsapp/mensagens',
  path: '/whatsapp/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappTemplatesRoute = WhatsappTemplatesRouteImport.update({
  id: '/whatsapp/templates',
  path: '/whatsapp/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmEventosIndexRoute = LlmEventosIndexRouteImport.update({
  id: '/llm/eventos/',
  path: '/llm/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmEventosAtorRoute = LlmEventosAtorRouteImport.update({
  id: '/llm/eventos/$ator',
  path: '/llm/eventos/$ator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/disparos/clientes': typeof DisparosClientesRoute
  '/disparos/mensagens': typeof DisparosMensagensRoute
  '/disparos/reguas': typeof DisparosReguasRoute
  '/whatsapp/mensagens': typeof WhatsappMensagensRoute
  '/whatsapp/templates': typeof WhatsappTemplatesRoute
  '/llm/': typeof LlmIndexRoute
  '/whatsapp/': typeof WhatsappIndexRoute
  '/llm/eventos/$ator': typeof LlmEventosAtorRoute
  '/llm/eventos/': typeof LlmEventosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/disparos/clientes': typeof DisparosClientesRoute
  '/disparos/mensagens': typeof DisparosMensagensRoute
  '/disparos/reguas': typeof DisparosReguasRoute
  '/whatsapp/mensagens': typeof WhatsappMensagensRoute
  '/whatsapp/templates': typeof WhatsappTemplatesRoute
  '/llm': typeof LlmIndexRoute
  '/whatsapp': typeof WhatsappIndexRoute
  '/llm/eventos/$ator': typeof LlmEventosAtorRoute
  '/llm/eventos': typeof LlmEventosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/disparos/clientes': typeof DisparosClientesRoute
  '/disparos/mensagens': typeof DisparosMensagensRoute
  '/disparos/reguas': typeof DisparosReguasRoute
  '/whatsapp/mensagens': typeof WhatsappMensagensRoute
  '/whatsapp/templates': typeof WhatsappTemplatesRoute
  '/llm/': typeof LlmIndexRoute
  '/whatsapp/': typeof WhatsappIndexRoute
  '/llm/eventos/$ator': typeof LlmEventosAtorRoute
  '/llm/eventos/': typeof LlmEventosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/precos'
    | '/disparos/clientes'
    | '/disparos/mensagens'
    | '/disparos/reguas'
    | '/whatsapp/mensagens'
    | '/whatsapp/templates'
    | '/llm/'
    | '/whatsapp/'
    | '/llm/eventos/$ator'
    | '/llm/eventos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/precos'
    | '/disparos/clientes'
    | '/disparos/mensagens'
    | '/disparos/reguas'
    | '/whatsapp/mensagens'
    | '/whatsapp/templates'
    | '/llm'
    | '/whatsapp'
    | '/llm/eventos/$ator'
    | '/llm/eventos'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/precos'
    | '/disparos/clientes'
    | '/disparos/mensagens'
    | '/disparos/reguas'
    | '/whatsapp/mensagens'
    | '/whatsapp/templates'
    | '/llm/'
    | '/whatsapp/'
    | '/llm/eventos/$ator'
    | '/llm/eventos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PrecosRoute: typeof PrecosRoute
  DisparosClientesRoute: typeof DisparosClientesRoute
  DisparosMensagensRoute: typeof DisparosMensagensRoute
  DisparosReguasRoute: typeof DisparosReguasRoute
  WhatsappMensagensRoute: typeof WhatsappMensagensRoute
  WhatsappTemplatesRoute: typeof WhatsappTemplatesRoute
  LlmIndexRoute: typeof LlmIndexRoute
  WhatsappIndexRoute: typeof WhatsappIndexRoute
  LlmEventosAtorRoute: typeof LlmEventosAtorRoute
  LlmEventosIndexRoute: typeof LlmEventosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disparos/clientes': {
      id: '/disparos/clientes'
      path: '/disparos/clientes'
      fullPath: '/disparos/clientes'
      preLoaderRoute: typeof DisparosClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disparos/mensagens': {
      id: '/disparos/mensagens'
      path: '/disparos/mensagens'
      fullPath: '/disparos/mensagens'
      preLoaderRoute: typeof DisparosMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disparos/reguas': {
      id: '/disparos/reguas'
      path: '/disparos/reguas'
      fullPath: '/disparos/reguas'
      preLoaderRoute: typeof DisparosReguasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm/': {
      id: '/llm/'
      path: '/llm'
      fullPath: '/llm/'
      preLoaderRoute: typeof LlmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/': {
      id: '/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof WhatsappIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/mensagens': {
      id: '/whatsapp/mensagens'
      path: '/whatsapp/mensagens'
      fullPath: '/whatsapp/mensagens'
      preLoaderRoute: typeof WhatsappMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/templates': {
      id: '/whatsapp/templates'
      path: '/whatsapp/templates'
      fullPath: '/whatsapp/templates'
      preLoaderRoute: typeof WhatsappTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm/eventos/': {
      id: '/llm/eventos/'
      path: '/llm/eventos'
      fullPath: '/llm/eventos/'
      preLoaderRoute: typeof LlmEventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm/eventos/$ator': {
      id: '/llm/eventos/$ator'
      path: '/llm/eventos/$ator'
      fullPath: '/llm/eventos/$ator'
      preLoaderRoute: typeof LlmEventosAtorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PrecosRoute: PrecosRoute,
  DisparosClientesRoute: DisparosClientesRoute,
  DisparosMensagensRoute: DisparosMensagensRoute,
  DisparosReguasRoute: DisparosReguasRoute,
  WhatsappMensagensRoute: WhatsappMensagensRoute,
  WhatsappTemplatesRoute: WhatsappTemplatesRoute,
  LlmIndexRoute: LlmIndexRoute,
  WhatsappIndexRoute: WhatsappIndexRoute,
  LlmEventosAtorRoute: LlmEventosAtorRoute,
  LlmEventosIndexRoute: LlmEventosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
